### ISSUE TITLE
Repository Settings Bug

### ISSUE THREAD

**Issue by raulalgo** [kactus-io/kactus#25]
In the Repository settings dialog, the "ignored files" crashes and gives this error

> Error: Unknown tab type: 2
    at Object.L.assertNever (file:///app/renderer.js:1:2618)
    at se.renderActiveTab (file:///app/renderer.js:32:143225)
    at se.render (file:///app/renderer.js:32:142459)
    at ae._renderValidatedComponentWithoutOwnerOrContext (file:///app/renderer.js:3:97251)
    at ae._renderValidatedComponent (file:///app/renderer.js:3:97388)
    at ae._updateRenderedComponent (file:///app/renderer.js:3:96638)
    at ae._performComponentUpdate (file:///app/renderer.js:3:96423)
    at ae.updateComponent (file:///app/renderer.js:3:95625)
    at ae.performUpdateIfNecessary (file:///app/renderer.js:3:94838)
    at Object.performUpdateIfNecessary (file:///app/renderer.js:1:65075)

> Version: 0.1.11
OS: Mac OS 10.12.5

**Comment by mathieudutour** [comment]
Oh forgot to remove the Kactus tab which is in another dialog now. Fixed in 0.1.12 (deploying now)
