### ISSUE TITLE
Issue building 'npm run build:dev' 

### ISSUE THREAD

**Issue by azpang** [kactus-io/kactus#64]
### Description

When I try to run 'npm run build:dev' I get these errors:
![image](https://user-images.githubusercontent.com/6273905/32383931-9a97e48c-c076-11e7-87d8-25a357e4dd27.png)

### Version

**Kactus version:** 0.2.10

**OS version:** macOS Sierra 10.12.6 

**Commit:** cd46b530c148b337592d7fa1c270eebb4115cb6b

### Steps to Reproduce

1. Run 'npm run build:dev'

**Expected behavior:** For it to build

**Actual behavior:** Threw Lifecycle errors and this... ```
[at-loader] ./app/src/lib/git/core.ts:253:26 
    TS2345: Argument of type 'GitError.ProtectedBranchDeleteRejected | GitError.ProtectedBranchRequiredStatus' is not assignable to parameter of type 'never'.
  Type 'GitError.ProtectedBranchDeleteRejected' is not assignable to type 'never'.
```


### Logs

> @ build:dev /Users/aaron_pang/Desktop/Projects/kactus
> npm run compile:dev && cross-env NODE_ENV=development ts-node script/build.ts


> @ compile:dev /Users/aaron_pang/Desktop/Projects/kactus
> cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js && npm run compile:plugin

[WEBPACK] Building 5 targets
[WEBPACK] Started building crash.js
[WEBPACK] Started building ask-pass.js
[WEBPACK] Started building main.js
[WEBPACK] Started building renderer.js
[WEBPACK] Started building cli.js

[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking started in a separate process...

[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
(node:57930) Warning: a promise was rejected with a non-error: [object Object]
[WEBPACK] Build failed after 13.974 seconds
(node:57930) Warning: a promise was rejected with a non-error: [object Object]
(node:57930) Warning: a promise was rejected with a non-error: [object Object]
[WEBPACK] Errors building cli.js
[at-loader] ./app/src/lib/git/core.ts:253:26 
    TS2345: Argument of type 'GitError.ProtectedBranchDeleteRejected | GitError.ProtectedBranchRequiredStatus' is not assignable to parameter of type 'never'.
  Type 'GitError.ProtectedBranchDeleteRejected' is not assignable to type 'never'.

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/aaron_pang/.nvm/versions/node/v7.8.0/bin/node" "/Users/aaron_pang/.nvm/versions/node/v7.8.0/bin/npm" "run" "compile:dev"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ compile:dev: `cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js && npm run compile:plugin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ compile:dev script 'cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js && npm run compile:plugin'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js && npm run compile:plugin
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaron_pang/.npm/_logs/2017-11-02T19_09_32_500Z-debug.log

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/aaron_pang/.nvm/versions/node/v7.8.0/bin/node" "/Users/aaron_pang/.nvm/versions/node/v7.8.0/bin/npm" "run" "build:dev"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:dev: `npm run compile:dev && cross-env NODE_ENV=development ts-node script/build.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:dev script 'npm run compile:dev && cross-env NODE_ENV=development ts-node script/build.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile:dev && cross-env NODE_ENV=development ts-node script/build.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaron_pang/.npm/_logs/2017-11-02T19_09_32_545Z-debug.log
US2169509-osx-2:kactus aaron_pang$ 
[at-loader] Checking finished with 1 errors

[at-loader] Checking finished with 1 errors

[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
[WEBPACK] fatal error occured
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at callback (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/worker-farm/lib/child/index.js:32:17)
    at finishedCallback (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/parallel-webpack/src/webpackWorker.js:114:32)
    at onCompiled (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/webpack/lib/Compiler.js:241:12)
    at applyPluginsAsync.err (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/tapable/lib/Tapable.js:202:11)
    at /Users/aaron_pang/Desktop/Projects/kactus/node_modules/awesome-typescript-loader/src/instance.ts:498:25
    at process._tickCallback (internal/process/next_tick.js:109:7)
(node:57934) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: channel closed
(node:57934) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
[WEBPACK] fatal error occured
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at callback (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/worker-farm/lib/child/index.js:32:17)
    at finishedCallback (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/parallel-webpack/src/webpackWorker.js:114:32)
    at onCompiled (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/webpack/lib/Compiler.js:241:12)
    at applyPluginsAsync.err (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/tapable/lib/Tapable.js:202:11)
    at /Users/aaron_pang/Desktop/Projects/kactus/node_modules/awesome-typescript-loader/src/instance.ts:498:25
    at process._tickCallback (internal/process/next_tick.js:109:7)
(node:57932) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: channel closed
(node:57932) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

US2169509-osx-2:kactus aaron_pang$ npm run build:dev

> @ build:dev /Users/aaron_pang/Desktop/Projects/kactus
> npm run compile:dev && cross-env NODE_ENV=development ts-node script/build.ts


> @ compile:dev /Users/aaron_pang/Desktop/Projects/kactus
> cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js && npm run compile:plugin

[WEBPACK] Building 5 targets
[WEBPACK] Started building ask-pass.js
[WEBPACK] Started building main.js
[WEBPACK] Started building crash.js
[WEBPACK] Started building cli.js
[WEBPACK] Started building renderer.js

[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from /Users/aaron_pang/Desktop/Projects/kactus/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking started in a separate process...

[at-loader] Checking started in a separate process...

[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
(node:57958) Warning: a promise was rejected with a non-error: [object Object]
[WEBPACK] Build failed after 13.563 seconds
(node:57958) Warning: a promise was rejected with a non-error: [object Object]
(node:57958) Warning: a promise was rejected with a non-error: [object Object]
[WEBPACK] Errors building cli.js
[at-loader] ./app/src/lib/git/core.ts:253:26 
    TS2345: Argument of type 'GitError.ProtectedBranchDeleteRejected | GitError.ProtectedBranchRequiredStatus' is not assignable to parameter of type 'never'.
  Type 'GitError.ProtectedBranchDeleteRejected' is not assignable to type 'never'.

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/aaron_pang/.nvm/versions/node/v7.8.0/bin/node" "/Users/aaron_pang/.nvm/versions/node/v7.8.0/bin/npm" "run" "compile:dev"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ compile:dev: `cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js && npm run compile:plugin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ compile:dev script 'cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js && npm run compile:plugin'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js && npm run compile:plugin
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaron_pang/.npm/_logs/2017-11-02T19_10_41_927Z-debug.log

[at-loader] Checking finished with 1 errors

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/aaron_pang/.nvm/versions/node/v7.8.0/bin/node" "/Users/aaron_pang/.nvm/versions/node/v7.8.0/bin/npm" "run" "build:dev"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:dev: `npm run compile:dev && cross-env NODE_ENV=development ts-node script/build.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:dev script 'npm run compile:dev && cross-env NODE_ENV=development ts-node script/build.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile:dev && cross-env NODE_ENV=development ts-node script/build.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaron_pang/.npm/_logs/2017-11-02T19_10_41_968Z-debug.log
US2169509-osx-2:kactus aaron_pang$ 
[at-loader] Checking finished with 1 errors

[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors

[at-loader] Checking finished with 1 errors
[WEBPACK] fatal error occured
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at callback (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/worker-farm/lib/child/index.js:32:17)
    at finishedCallback (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/parallel-webpack/src/webpackWorker.js:114:32)
    at onCompiled (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/webpack/lib/Compiler.js:241:12)
    at applyPluginsAsync.err (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/Users/aaron_pang/Desktop/Projects/kactus/node_modules/tapable/lib/Tapable.js:202:11)
    at /Users/aaron_pang/Desktop/Projects/kactus/node_modules/awesome-typescript-loader/src/instance.ts:498:25
    at process._tickCallback (internal/process/next_tick.js:109:7)
(node:57960) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: channel closed
(node:57960) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mathieudutour** [comment]
I think I fixed it, could you pull and try again? (might need an `npm i`)
